#**Start Machine Learning with Scikit-Learn**


---



1. Making Machine Learning model - Predicting the varieties of irises.
2. Learn Scikit-Learn based framework
3. Model_Selection  

##**1. Making Machine Learning model - Predicting the varieties of irises.**
    Create a data set -> load_iris()
    ML algorithm -> DecisionTreeClassifier
    Separate data into train data and test data -> train_test_split()

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd

# Load iris data
iris = load_iris()

# iris.data has data with only features as a numpy
iris_data = iris.data

# iris.target has label(decided value)data as a numpy
iris_label = iris.target
print('iris target\'s value:', iris_label)
print('iris target\'s name:', iris.target_names)

# Convert to DataFrame
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target's value: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target's name: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0

[3 rows x 5 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

In [ ]:
dtc = DecisionTreeClassifier(random_state = 11)
dtc.fit(x_train, y_train)
pred = dtc.predict(x_test)
from sklearn.metrics import accuracy_score
print("accuracy_score: %.4f" %accuracy_score(y_test, pred))

accuracy_score: 0.9333


##**2. Learn Scikit-Learn based framework**


1.   Understanding of Estimator, fit( ), predict( )
2.   The main process of building a Machine Learning model



### 1.   Understanding of Estimator, fit( ), predict( )
    Model Learning -> fit()
    Prediction of the learned model -> predict()
    Classification algorithm -> Classifer
    Regression algorithm -> Regressor
    Classifier + Regressor = Estimator(A class that implements all algorithms of supervised learning)
    Estimater implements fit() and predict() internally
    

### 2. The main process of building a Machine Learning model
    1. Feature processing(processing, changing, extracting)
    2. ML algorithm train/predict
    3. Model evaluation

## **3. Model_Selection**  
    Seperate train data and test data, cross-validation division and evaluation, tune Estimator's hyper parameter


1.   train_test_split( )
2.   cross-validation
3.   GridSearchCV
4.   Data Preprocessing
5.   Feature Scaling and Normalization


### 1. train_test_split( )

      ※Core parameters: test_size, random_state
        test_size -> test_data size / whole data size
        random_state -> Create the same training/test data set every time 

In [ ]:
train_data = iris.data
train_label = iris.target
dtc.fit(train_data, train_label)

pred = dtc.predict(train_data)
print("accuracy_score:", accuracy_score(pred, train_label))

accuracy_score: 1.0


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(train_data, train_label, test_size = 0.3, random_state = 121)
dtc.fit(x_train, y_train)
pred = dtc.predict(x_test)
print("accuracy_score: %.4f" %accuracy_score(y_test,pred))

accuracy_score: 0.9556


### 2. cross-validation
    Used for improve overfitting
    overfitting: When the model is excessively optimized only for train data and actual prediction is performed with other data,
                 the prediction performance is excessively low.
    Train data -> Train data + Validation data

* KFOLD cross-validation
      Create k data fold sets and repeatedly perform training and verification evaluations on each fold set as many as k times.

      data set(k=5)
      Train, Train, Train, Train, Valid -> verification evaluation1(eval1)
      Train, Train, Train, Valid, Train -> verification evaluation2(eval2)
      Train, Train, Valid, Train, Train -> verification evaluation3(eval3)
      Train, Valid, Train, Train, Train -> verification evaluation4(eval4)
      Valid, Train, Train, Train, Train -> verification evaluation5(eval5)
      Final evaluation = mean(eval[1,2,3,4,5])

      kfold.split() -> split learning data into learning data and validation data
      return value: index 
                                                        

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dtc = DecisionTreeClassifier(random_state = 156)

kfold = KFold(n_splits = 5)
print("iris data's size:", features.shape[0])

iris data's size: 150


In [ ]:
n_iter = 0
cv_accuracy = []
for train_index, test_index in kfold.split(features):
  x_train, x_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  dtc.fit(x_train, y_train)
  pred = dtc.predict(x_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred),4)
  cv_accuracy.append(accuracy) 
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]
  print("\n#{0} validation accuracy:{1}, train_data size:{2}, test_data size:{3}".format(n_iter, accuracy, train_size, test_size))
  print("\n#{0} validation_data index:{1}".format(n_iter, test_index))
print("\n## Final evaluation:", np.mean(cv_accuracy))



#1 validation accuracy:1.0, train_data size:120, test_data size:30

#1 validation_data index:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 validation accuracy:0.9667, train_data size:120, test_data size:30

#2 validation_data index:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 validation accuracy:0.8667, train_data size:120, test_data size:30

#3 validation_data index:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 validation accuracy:0.9333, train_data size:120, test_data size:30

#4 validation_data index:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 validation accuracy:0.7333, train_data size:120, test_data size:30

#5 validation_data index:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 14

* Stratified KFold
      The k-fold method for label datasets with unbalanced distribution
      Frequently used in Classification problems
      Not supported in Regression
      Split (train_data) into (train_data) and (validation_data) by (label_data)'s distribution
      -> StratifiedKFold.split() -> parameters: feature_data, label_data
                   KFold.split() -> parameters: feature_data
      

In [ ]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [ ]:
kfold = KFold(n_splits = 3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print("## cross-validation: {0}".format(n_iter))
  print("train_label_data's distribution:\n", label_train.value_counts())
  print("test_label_data's distribution:\n", label_test.value_counts())
  print()

## cross-validation: 1
train_label_data's distribution:
 2    50
1    50
Name: label, dtype: int64
test_label_data's distribution:
 0    50
Name: label, dtype: int64

## cross-validation: 2
train_label_data's distribution:
 2    50
0    50
Name: label, dtype: int64
test_label_data's distribution:
 1    50
Name: label, dtype: int64

## cross-validation: 3
train_label_data's distribution:
 1    50
0    50
Name: label, dtype: int64
test_label_data's distribution:
 2    50
Name: label, dtype: int64



In [ ]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print("## cross-validation: {0}".format(n_iter))
  print("train_label_data's distribution:\n", label_train.value_counts())
  print("test_label_data's distribution:\n", label_test.value_counts())
  print()

## cross-validation: 1
train_label_data's distribution:
 2    34
1    33
0    33
Name: label, dtype: int64
test_label_data's distribution:
 1    17
0    17
2    16
Name: label, dtype: int64

## cross-validation: 2
train_label_data's distribution:
 1    34
2    33
0    33
Name: label, dtype: int64
test_label_data's distribution:
 2    17
0    17
1    16
Name: label, dtype: int64

## cross-validation: 3
train_label_data's distribution:
 0    34
2    33
1    33
Name: label, dtype: int64
test_label_data's distribution:
 2    17
1    17
0    16
Name: label, dtype: int64



In [ ]:
n_iter = 0
cv_accuracy = []
for train_index, test_index in skf.split(features, label):
  x_train, x_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  dtc.fit(x_train, y_train)
  pred = dtc.predict(x_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred),4)
  cv_accuracy.append(accuracy) 
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]
  print("\n#{0} validation accuracy:{1}, train_data size:{2}, test_data size:{3}".format(n_iter, accuracy, train_size, test_size))
  print("\n#{0} validation_data index:{1}".format(n_iter, test_index))
print("\n## Final evaluation:", np.mean(cv_accuracy))



#1 validation accuracy:0.98, train_data size:100, test_data size:50

#1 validation_data index:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 validation accuracy:0.94, train_data size:100, test_data size:50

#2 validation_data index:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 validation accuracy:0.98, train_data size:100, test_data size:50

#3 validation_data index:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## Final evaluation: 0.9666666666666667


* cross_val_score( )
      cross-validation API
      Use Stratified KFold: Classfier
                     KFold: Regressor
      cross_val_score(estinamter, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
      ※Core parameters: estimator, X, y, scoring, cv
        estimatior -> Classifier or Regressor
        X -> Feature_data
        y -> Label_data
        scoring -> Evaluation metrics
        cv -> Number of cross-validation folds
       return -> Evaluation value with metrics
        

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

iris_data = load_iris()
dtc = DecisionTreeClassifier(random_state = 156)

data = iris.data
label = iris.target

scores = cross_val_score(dtc, data, label, scoring = 'accuracy', cv=3)
print("cross-validation score:", np.round(scores,4))
print("mean(cross-validation score):", np.round(np.mean(scores),4))

cross-validation score: [0.98 0.94 0.98]
mean(cross-validation score): 0.9667


### 3.   GridSearchCV
    API that can derive optimal parameters
    ※Core parameters: estimator, param_grid, scoring, cv, refit
    estimator -> Classifier, Regressosr, Pipeline
    param_grid -> dictionary(key + list)
                  key: parameter name(str), value: parameter value(list)
    scoring -> Evaluation metrics
    cv -> Number of cross-validation folds
    refit -> If true, find optimal hyperparameter, re-train the entered estimator object with the corresponding hyperparameters

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.2 ,random_state = 121)
dtc = DecisionTreeClassifier()
parameters = {'max_depth': [1,2,3], 'min_samples_split': [2,3]}

In [ ]:
import pandas as pd
grid_dtc = GridSearchCV(dtc, param_grid = parameters, cv = 3, refit = True)
grid_dtc.fit(x_train, y_train)

scores_df = pd.DataFrame(grid_dtc.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  ...  split2_test_score
0  {'max_depth': 1, 'min_samples_split': 2}  ...               0.70
1  {'max_depth': 1, 'min_samples_split': 3}  ...               0.70
2  {'max_depth': 2, 'min_samples_split': 2}  ...               0.95
3  {'max_depth': 2, 'min_samples_split': 3}  ...               0.95
4  {'max_depth': 3, 'min_samples_split': 2}  ...               0.95
5  {'max_depth': 3, 'min_samples_split': 3}  ...               0.95

[6 rows x 6 columns]

* best_params_, best_score_, best_estimator_
      best_params_ -> Hyperparameter values representing the highest performance
      best_score_ -> Evaluation result representing the highest performance
      best_estimator_ -> Learn estimator as a hyperparameter that represents optimal performance and save it as a best_estimator_

In [ ]:
estimator = grid_dtc.best_estimator_
pred = estimator.predict(x_test)
print("Accuracy: %.4f" %accuracy_score(y_test, pred))
print("hyperparameters:", grid_dtc.best_params_)

Accuracy: 0.9667
hyperparameters: {'max_depth': 3, 'min_samples_split': 2}


##**4. Data Preprocessing**

    Process Null(NaN) value -> NaN is not allowed
    Convert string to number -> In Scikit-Learn's ML algorithm, string values are not allowed as input values

1.   Label encoding
2.   One-Hot encoding
3.   Feature Scaling and Normalizer
4.   Precautions for scaling conversion of training data and test data




    















### 1. Label encoding
      Convert category features to code-type numerical values
      ex) category features: a,b,c,d,e
          After label encoding -> a:1, b:2, c:3, d:4, e:5

      In a particular ML algorithm, the predictive performance is poor because the characteristics of large and small work for numerical values
      So, don't apply label encoding to ML algorithm such as linear regression
      Tree-based algorithm -> Does not reflect the characteristics of large and small numbers: No problem for label encoding
      Solution: One-Hot encoding
      

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
items = ['TV', 'refrigerator', 'oven', 'computer', 'electric fan', 'electric fan', 'mixer', 'mixer']
le.fit(items)
labels = le.transform(items)
print("Before label encoding:", items)
print("After label encoding:", labels)

Before label encoding: ['TV', 'refrigerator', 'oven', 'computer', 'electric fan', 'electric fan', 'mixer', 'mixer']
After label encoding: [0 5 4 1 2 2 3 3]


In [ ]:
print('encoding class:', le.classes_)
print("                [ 0        1            2          3       4          5      ]")

encoding class: ['TV' 'computer' 'electric fan' 'mixer' 'oven' 'refrigerator']
                [ 0        1            2          3       4          5      ]


In [ ]:
print('decoding value:', le.inverse_transform([0,5,4,1,2,2,3,3]))

decoding value: ['TV' 'refrigerator' 'oven' 'computer' 'electric fan' 'electric fan'
 'mixer' 'mixer']


### 2. One-Hot encoding
      Depending on the type of feature value,
      a new feature is added to display 1 only in columns corresponding to unique values and 0 in the remaining columns
      
      Before applying One-Hot encoding,
      1. Convert all string values to numerical values
      2. 2D data is needed for input values
      

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items = ['TV', 'refrigerator', 'oven', 'computer', 'electric fan', 'electric fan', 'mixer', 'mixer']

#1. Convert all string values to numerical values
le = LabelEncoder()
le.fit(items)
labels = le.transform(items)

#2. 2D data is needed for input values 
labels = labels.reshape(-1,1)

#3. Apply One-Hot encoding
ohe = OneHotEncoder()
ohe.fit(labels)
ohe_labels = ohe.transform(labels)
print("One-Hot encoding data:\n", ohe_labels.toarray())
print()
print("Dimension of One-Hot encoding data:\n", ohe_labels.shape )

One-Hot encoding data:
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]

Dimension of One-Hot encoding data:
 (8, 6)


In [ ]:
ohe_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

* get_dummies( )
      API, which supports One-Hot encoding more easily

In [ ]:
import pandas as pd
df = pd.DataFrame({'item' : ['TV', 'refrigerator', 'oven', 'computer', 'electric fan', 'electric fan', 'mixer', 'mixer']})
pd.get_dummies(df)

item_TV  item_computer  ...  item_oven  item_refrigerator
0        1              0  ...          0                  0
1        0              0  ...          0                  1
2        0              0  ...          1                  0
3        0              1  ...          0                  0
4        0              0  ...          0                  0
5        0              0  ...          0                  0
6        0              0  ...          0                  0
7        0              0  ...          0                  0

[8 rows x 6 columns]

### 3. Feature Scaling and Normalizer
    Feature Scaling -> StandardScaler(Standardization), MinMaxScaler(Normalization)
    Normalizer -> Normalization of the concept of linear algebra(Vector normalization)
    

* Standardization, Normalization, Normalizer
      < Standardization >
      Convert each data feature to a value
      with a Gaussian normal distribution with a mean of 0 and a variance of 1
      
      x_new = (x - mean(x)) / std(x)

      < Normalization >
      Transform the sizes to unify the sizes of different features(min:0, max:1)

      x_new = (x - min(x)) / (max(x) - min(x))

      < Normalizer >
      Transform to size individual vectors

      x_new = x / sqrt(x^2 + y^2 + z^2)


* StandardScaler
      Convert each data feature with a mean of 0 and a variance of 1
      ML algorithm(SVM, Linear Regression, Logistic Regression) is implemented assuming that data has Gaussian distribution
      If standardization is applied: DataFrame -> Numpy.ndarray
      The fit() and transform() of StandardScaler can only be done with 2D or higher data

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)

print("mean_features")
print(iris_df.mean())
print()
print("variance_features")
print(iris_df.var())

mean_features
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

variance_features
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(iris_df)
iris_scaled = sc.transform(iris_df)

iris_df_scaled = pd.DataFrame(iris_scaled, columns = iris.feature_names)
print("mean_features")
print(iris_df_scaled.mean())
print()
print("variance_features")
print(iris_df_scaled.var())

mean_features
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

variance_features
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* MinMaxScaler
      Transform the size of features(min:0, max:1)
      If there's a negative value, (min:-1, max:1)
      If Normalization is applied: DataFrame -> Numpy.ndarray
      The fit() and transform() of MinMaxScaler can only be done with 2D or higher data

In [ ]:
from sklearn.preprocessing import MinMaxScaler
msc = MinMaxScaler()
msc.fit(iris_df)
iris_scaled = msc.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print("min_features")
print(iris_df_scaled.min())
print()
print("max_features")
print(iris_df_scaled.max())


min_features
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

max_features
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 4. Precautions for scaling conversion of training data and test data
      fit() -> Setting standard information for data conversion
      transform() -> Convert data with set information
      * Problems
      ex) sc.fit(x_train)
          sc.transform(x_test)
          -> sc is applied to x_train(standard information for data conversion: train_data)
             test_data's scaling standard information is different from train_data's 
             So, transform(x_test) fail to derive the correct prediction results

* Problems when scaling
      train_array's [1, 2, 3, 4, 5] -> [0.1, 0.2, 0.3, 0.4, 0.5]
      test_array's [1, 2, 3, 4, 5] -> [0.2, 0.4, 0.6, 0.8, 1]
      Scaled result is different between train_data and test_data

      

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [ ]:
msc = MinMaxScaler()
msc.fit(train_array)
train_scaled = msc.transform(train_array)
print("original train_data:", train_array.reshape(-1))
print("scaled train_data:", np.round(train_scaled.reshape(-1),2))

original train_data: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled train_data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
msc.fit(test_array)
test_scaled = msc.transform(test_array)
print("original test_data:", test_array.reshape(-1))
print("scaled test_data:", np.round(test_scaled.reshape(-1),2))

original test_data: [0 1 2 3 4 5]
scaled test_data: [0.  0.2 0.4 0.6 0.8 1. ]


* Solutions for problems
       ML models are learned based on train data, test data must follow the scaling criteria of train data

In [ ]:
msc = MinMaxScaler()
msc.fit(train_array)
train_scaled = msc.transform(train_array)

print("original train_data:", train_array.reshape(-1))
print("scaled train_data:", np.round(train_scaled.reshape(-1),2))
print()

test_scaled = msc.transform(test_array)
print("original test_data:", test_array.reshape(-1))
print("scaled test_data:", np.round(test_scaled.reshape(-1),2))

original train_data: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled train_data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

original test_data: [0 1 2 3 4 5]
scaled test_data: [0.  0.1 0.2 0.3 0.4 0.5]
