#**Understanding of Machine Learning**


---



1.   Classification of Machine Learning
2.   Numpy
3.   Data Handling - Pandas

##**1. Classification of Machine Learning**



*   **Supervised - Learning**

1.   Classification
2.   Regression
3.   Recommendation System
4.   Visual/Speech recognition
5.   Text Analysis, NLP


*   **Unsupervised - Learning**

1.   Clustering
2.   Dimension Reduction
3.   Reinforcement Learning





##**2. Numpy**

    Numpy, which means numerical Python, is a representative package that helps Python create linear algebra-based programs easily.
    Understanding Numpy is so important in python-based Machine Learning. 


1.   Overview of Numpy
2.   Ndarray's data type
3.   Create ndarray comfortably - arange, zeros, ones
4.   To change the dimension and size of ndarray - reshape()
5.   Choose ndarray's dataset - indexing
6.   Sort of matrix - sort(), argsort()
7.   Linear algebra operation - Inner product and transposed matrix



### 1. Overview of Numpy



* Numpy-based data type = ndarray
* Shape -> Form of a tuple(row,columns) 
* ndarray.ndim

In [ ]:
import numpy as np
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1.shape: ', array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print('array2 type: ', type(array2))
print('array2.shape: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3.shape: ', array3.shape)

print("array1: {0}-dimensional, array2: {1}-dimensional, array3: {2}-dimensional".format(array1.ndim, array2.ndim, array3.ndim))

array1 type:  <class 'numpy.ndarray'>
array1.shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2.shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3.shape:  (1, 3)
array1: 1-dimensional, array2: 2-dimensional, array3: 2-dimensional


### 2. ndarray's data type

     Only the same data type can be used in ndarray 
     If other data types are mixed, type conversion is applied to data types with larger data sizes

* ndarray.dtype()
      Type conversion is applied to data types with larger data sizes

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64




*   ndarray.astype()
        Change the type of data for saving memory 




In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 3.   Create ndarray comfortably - arange, zeros, ones
    Used to create data primarily for testing or to initialize large amounts of data collectively.

* arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4. To change the dimension and size of ndarray - reshape()
    If -1 is used as a factor, it's going to be a new type that's compatible with ndarray. 
    reshape(-1,1) -> ndarray must be converted into 2-dimensional in any form with 1 column no matter how many rows it has.
                     In conclusion, converting to 1-dimensional arrangement.

* reshape

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* Use -1 factor in reshape

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2.shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


*  reshape(-1, 1)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3-dimensional -> 2-dimensional
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5.shape:', array5.shape)

#1-dimensional -> 2-dimensional
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6.shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)


### 5.   Choose ndarray's dataset - indexing
    * Extract only specific data: Specify the desired index value, return the location data.
    * Slicing: Extracting ndarrays on a continuous index.
    * Fancy indexing: A certain set of indexes is designated in the form of a list or ndarray and returns the ndarray of the data in the corresponding location.
    * Boolean indexing: Returns the end of data at the index location corresponding to the true based on a set of true/false value indexes that correspond to a specific condition.

* Extract only specific data

In [ ]:
array1 = np.arange(1,10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))
print('The first value from the back: {0}, The second value from the back: {1}'.format(array1[-1],array1[-2]))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
The first value from the back: 9, The second value from the back: 8


In [ ]:
array2d = array1.reshape(3,3)
print(array2d)
value = array2d[1,1]
print('array2d[1,1]:',value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[1,1]: 5


* Slicing

In [ ]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
print('array2d:\n', array2d)
print('array2d[0:2,0:2]:\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]:\n',array2d[1:3,0:3])
print('array2d[:,:]:\n',array2d[:,:])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]:
 [[1 2]
 [4 5]]
array2d[1:3,0:3]:
 [[4 5 6]
 [7 8 9]]
array2d[:,:]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0].shape:', array2d[0].shape, 'array2d[1].shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0].shape: (3,) array2d[1].shape: (3,)


* Fancy indexing

In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [ ]:
array1d = np.arange(1,10)
print('array1d:', array1d)
print('array1d>5:', array1d>5)
array3 = array1d[array1d>5]
print('array1d>5 boolean indexing values:', array3)

array1d: [1 2 3 4 5 6 7 8 9]
array1d>5: [False False False False False  True  True  True  True]
array1d>5 boolean indexing values: [6 7 8 9]


In [ ]:
indexes1 = np.array([5,6,7,8])
indexes2 = [5,6,7,8]
array4_1 = array1d[indexes1]
array4_2 = array1d[indexes2]
print(array4_1)
print(array4_2)

[6 7 8 9]
[6 7 8 9]


###6. Sort of matrix - sort(), argsort()
    default = ascending sort
    ex) [3,1,9,5] -> [1,3,5,9]    
    Sort by raw or column using axis
    argsort() -> Use when an original matrix is sorted and an index for an element of an existing original matrix is required.
                 Very useful in Numpy

    

* ndarray.sort()

In [ ]:
org_array = np.array([3,1,9,5])
print("original_array:", org_array)

sort_array_1 = org_array.sort()
print("original_array:", org_array)
print("sort_array1:", sort_array_1)

original_array: [3 1 9 5]
original_array: [1 3 5 9]
sort_array1: None


* np.sort()

In [ ]:
org_array = np.array([3,1,9,5])
print("original_array:", org_array)

sort_array_2 = np.sort(org_array)
print("original_array:", org_array)
print("sort_array2:", sort_array_1)

original_array: [3 1 9 5]
original_array: [3 1 9 5]
sort_array2: None


* Descending sort -> np.sort[::-1]

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print("Descending sort array:", sort_array1_desc)

Descending sort array: [9 5 3 1]


* Sort the 2-dimensional or higher matrix

In [ ]:
array2d = np.array([[8,12],[7,1]])
print('array2d:\n', array2d)

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('Sorted by raw(axis=0):\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('Sorted by column(axis=1):\n', sort_array2d_axis1)

array2d:
 [[ 8 12]
 [ 7  1]]
Sorted by raw(axis=0):
 [[ 7  1]
 [ 8 12]]
Sorted by column(axis=1):
 [[ 8 12]
 [ 1  7]]


* argsort() 

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(org_array)
print(sort_array_2)
print('index for an element of an existing original matrix when it is ascending sorted:', sort_indices)

<class 'numpy.ndarray'>
[3 1 9 5]
[1 3 5 9]
index for an element of an existing original matrix when it is ascending sorted: [1 0 3 2]


In [ ]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices))
print(org_array)
print(sort_array1_desc)
print('index for an element of an existing original matrix when it is descending sorted:', sort_indices_desc)

<class 'numpy.ndarray'>
[3 1 9 5]
[9 5 3 1]
index for an element of an existing original matrix when it is descending sorted: [2 3 0 1]


### 7.   Linear algebra operation - Inner product and transposed matrix

* Inner product -> np.dot()

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print("Inner product result:\n", np.dot(A,B))

Inner product result:
 [[ 58  64]
 [139 154]]


* Transposed matrix

In [ ]:
A = np.array([[1,2],[3,4]])
transpose_mat = np. transpose(A)
print('Transposed matrix:\n', transpose_mat)

Transposed matrix:
 [[1 3]
 [2 4]]


##**3.   Data Handling - Pandas**
    Pandas provides a variety of great features to efficiently process 2D data.
    The core object of Pandas is DataFrame
    Before understanding the DataFrame, it is important to understand the index and series
    Index -> A key value that uniquely identifies individual data
    Series -> A structure with only one column
    DataFrame -> A structure with lots of columns
    url(Data for this chapter): 'https://www.kaggle.com/c/titanic/data'

1.   Pandas - fundamental API
2.   Interchange between DataFrame, List, Dictionary and ndarray
3.   Delete Data
4.   Index
5.   Data Selection and Filtering
6.   Sorting, Aggregation, GroupBy
7.   Process missing data
8.   Data processing with apply lambda

### 1. Pandas - fundamental API

* read_csv() - Loading data with DataFrame

In [ ]:
import pandas as pd
titanic_df = pd.read_csv('train.csv')

* head() -> Return some data(Default:5)

In [ ]:
titanic_df.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]

* shape() -> Return the size of rows and columns in a DataFrame

In [ ]:
print('DataFrame\'s size: ', titanic_df.shape)

DataFrame's size:  (891, 12)


* info() -> row data size, column data size, data type, Null size

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


* describe() -> Not Null size, mean, std, min, max, (25%, 50%, 75% values) 
      Only the distribution of numeric columns(int, float) is investigated,
      and object-type columns are excluded from the output.  
                

In [ ]:
titanic_df.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

* value_counts() -> Return the number of data values of a specified column
      value_counts can only be called on series objects
      ex) DataFrame[column].value_counts

In [ ]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

* sort_values()
      ※ by -> Column for sorting
         ex) DataFrame.sort_values(by=[column1, columns2 ..])
         ascending = True -> ascending order
                     False -> descending order 

In [ ]:
titanic_df.sort_values(by='Pclass', ascending = False)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
511          512         0       3  ...   8.0500   NaN         S
500          501         0       3  ...   8.6625   NaN         S
501          502         0       3  ...   7.7500   NaN         Q
502          503         0       3  ...   7.6292   NaN         Q
..           ...       ...     ...  ...      ...   ...       ...
102          103         0       1  ...  77.2875   D26         S
710          711         1       1  ...  49.5042   C90         C
711          712         0       1  ...  26.5500  C124         S
712          713         1       1  ...  52.0000  C126         S
445          446         1       1  ...  81.8583   A34         S

[891 rows x 12 columns]

### 2.   Transforming between DataFrame, List, Dictionary and ndarray
    Many API of Scikit-Learn use the ndarray as an input factor
    So, transforming between DataFrame and ndarray occurs very frequently

* Transforming ndarray, List to DataFrame
      Must designate column's name for the DataFrame

In [ ]:
import numpy as np
list1 = [1,2,3]
array1 = np.array(list1)
df_list1 = pd.DataFrame(list1, columns = ['col1'])
df_array1 = pd.DataFrame(array1, columns = ['col1'])
print("List -> DataFrame:\n", df_list1)
print("ndarray -> DataFrame:\n", df_array1)

List -> DataFrame:
    col1
0     1
1     2
2     3
ndarray -> DataFrame:
    col1
0     1
1     2
2     3


* Transforming Dictionary to DataFrame
      Dictionary ->  DataFrame
         Key     ->   columns
        value    ->    data  

In [ ]:
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print("Dictionary -> DataFrame:\n", df_dict)

Dictionary -> DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


* Transforming DataFrame to ndarray
      Transforming into ndarray using values is very important!

In [ ]:
array3 = df_dict.values
print("DataFrame -> ndarray:\n", array3)

DataFrame -> ndarray:
 [[ 1  2  3]
 [11 22 33]]


* Transforming DataFrame to List, Dictionary
      * DataFrame -> List
        DataFrame.values.tolist()
      * DataFrame -> Dictionary
        DataFrame.to_dict('list')

In [ ]:
list3 = df_dict.values.tolist()
print("DataFrame -> List:\n", list3)
dict3 = df_dict.to_dict('list')
print("DataFrame -> Dictionary:\n", dict3)

#If don't use 'list' in to_dict
dict_3_error = df_dict.to_dict()
print("DataFrame -> Dictionary(error mode):\n", dict_3_error)

DataFrame -> List:
 [[1, 2, 3], [11, 22, 33]]
DataFrame -> Dictionary:
 {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
DataFrame -> Dictionary(error mode):
 {'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}


### 3. Delete Data
    DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
    ※Core parameters: labels, axis, inplace
      labels -> column to delete 
      axis = 0 -> Drop the specific row : Use when delete outlier data
             1 -> Drop the specific column : Primarily use
      inplace = True -> Drop on original DataFrame
              = False -> Original DataFrame is maintained

In [ ]:
titanic_df.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]

* Drop by columns

In [ ]:
titanic_drop_df_column = titanic_df.drop('Age', axis = 1)
titanic_drop_df_column.head(1)

PassengerId  Survived  Pclass  ...  Fare Cabin  Embarked
0            1         0       3  ...  7.25   NaN         S

[1 rows x 11 columns]

* Drop by rows

In [ ]:
titanic_drop_df_row = titanic_df.drop([0],axis = 0)
titanic_drop_df_row.head(1)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1            2         1       1  ...  71.2833   C85         C

[1 rows x 12 columns]

### 4. Index
    An object that uniquely identifies a record of DataFrame, Series.
    Index objects cannot be changed

* Extract index

In [ ]:
titanic_df = pd.read_csv('train.csv')
indexes = titanic_df.index
print(indexes)
print(indexes.values[:10])

RangeIndex(start=0, stop=891, step=1)
[0 1 2 3 4 5 6 7 8 9]


* reset_index()
      A new index is assigned as a continuous numeric type, and the existing index is added as a new column name, 'index'
      If the index is not continuous 'int' type data, it is mainly used to turn it back into continuous 'int' type data.
      When reset_index() is applied to a Series, DataFrame is converted.
      ※ parameters: drop
         (drop = True) -> Existing indexes are not added as new columns and the series remains the same.

In [ ]:
titanic_reset_df = titanic_df.reset_index(inplace = False)
titanic_reset_df.head(3)

index  PassengerId  Survived  ...     Fare Cabin Embarked
0      0            1         0  ...   7.2500   NaN        S
1      1            2         1  ...  71.2833   C85        C
2      2            3         1  ...   7.9250   NaN        S

[3 rows x 13 columns]

In [ ]:
print("### Before reset_index ###")
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print("type => ", type(value_counts))
print()
print("### After reset_index ###")
new_value_counts = value_counts.reset_index(inplace = False)
print(new_value_counts)
print("type => ", type(new_value_counts))

### Before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
type =>  <class 'pandas.core.series.Series'>

### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
type =>  <class 'pandas.core.frame.DataFrame'>


In [ ]:
print("### (drop = True) ###")
new_value_counts2 = value_counts.reset_index(inplace = False, drop = True)
print(new_value_counts2)
print("type => ", type(new_value_counts2))

### (drop = True) ###
0    491
1    216
2    184
Name: Pclass, dtype: int64
type =>  <class 'pandas.core.series.Series'>


### 5.   Data Selection and Filtering
    iloc[] -> Location-based indexing
              Use integar type as row and column value
              Don't provide boolean indexing
    loc[] -> Name-based indexing
             loc[row, column]
             row : DataFrame's index, column : column's name
    DataFrame[] -> Column name, Index can go into []operator
    

* Extract column data - Column name

In [ ]:
print("Single column extraction")
print(titanic_df['Pclass'].head(3))
print()
print("Several columns extraction")
print(titanic_df[['Pclass','Survived']].head(3))

#print(titanic_df[0])-> If you just enter a number value, it's an error.

Single column extraction
0    3
1    1
2    3
Name: Pclass, dtype: int64

Several columns extraction
   Pclass  Survived
0       3         0
1       1         1
2       3         1


* Extract row data - Slicing

In [ ]:
titanic_df[0:2]

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

* Extract data by boolean indexing

In [ ]:
titanic_df['Pclass']==3

0       True
1      False
2       True
3      False
4       True
       ...  
886    False
887    False
888     True
889    False
890     True
Name: Pclass, Length: 891, dtype: bool

In [ ]:
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
0            1         0       3  ...  7.250   NaN         S
2            3         1       3  ...  7.925   NaN         S
4            5         0       3  ...  8.050   NaN         S

[3 rows x 12 columns]

* iloc

In [ ]:
data = {'name':['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']}
data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'four'])
data_df

name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [ ]:
print("data_df.iloc[0,0]:{0}, data_df.iloc[1,1]:{1}, data_df.iloc[2,2]:{2}".format(data_df.iloc[0,0],data_df.iloc[1,1],data_df.iloc[2,2]))

data_df.iloc[0,0]:Chulmin, data_df.iloc[1,1]:2016, data_df.iloc[2,2]:Male


In [ ]:
data_df_reset = data_df.reset_index(inplace = False)
data_df_reset.index = data_df_reset.index +1
data_df_reset

index      name  Year  Gender
1    one   Chulmin  2011    Male
2    two  Eunkyung  2016  Female
3  three  Jinwoong  2015    Male
4   four   Soobeom  2015    Male

In [ ]:
data_df_reset.iloc[0,1]

'Chulmin'

In [ ]:
data_df_reset.iloc[1:3, 1]

2    Eunkyung
3    Jinwoong
Name: name, dtype: object

* loc

In [ ]:
data_df.loc['one','name']

'Chulmin'

In [ ]:
data_df_reset.loc[1,'name']

'Chulmin'

In [ ]:
data_df_reset.loc[1:3, 'name']

1     Chulmin
2    Eunkyung
3    Jinwoong
Name: name, dtype: object

* loc with boolean index

In [ ]:
titanic_df.loc[titanic_df['Age']>60, ['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

### 6.   Sorting, Aggregation, GroupBy

* sort_values( )
      Sorting of DataFrame, Series
      ※Core parameters: by, ascending, inplace
        by -> If enter a specific column, sort it with that column
        ascending = True -> ascending order(Default)
                  = False -> descending order

In [ ]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
845          846         0       3  ...   7.55   NaN         S
746          747         0       3  ...  20.25   NaN         S
279          280         1       3  ...  20.25   NaN         S

[3 rows x 12 columns]

In [ ]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending = False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass  ...  Fare Cabin  Embarked
868          869         0       3  ...   9.5   NaN         S
153          154         0       3  ...  14.5   NaN         S
282          283         0       3  ...   9.5   NaN         S

[3 rows x 12 columns]

* Aggregation( )
      min(), max(), sum(), count() -> aggregation
      If apply the aggregation to the DataFrame, the aggregation is applied to all columns

In [ ]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

* groupby( )
      When groupby is applied, return the DataFrame Groupby Object
      If the aggregation is applied to the result of applying the groupby to the DataFrame, the aggregation is applied to all columns except for the groupby target column

In [ ]:
titanic_groupby = titanic_df.groupby(by = 'Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [ ]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  ...  Ticket  Fare  Cabin  Embarked
Pclass                                    ...                               
1               216       216   216  216  ...     216   216    176       214
2               184       184   184  184  ...     184   184     16       184
3               491       491   491  491  ...     491   491     12       491

[3 rows x 11 columns]

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [ ]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 7.   Process missing data
    missing data = Null(NaN)
    isna() -> Check if it's NaN or not
    fillna() -> Replace NaN with another value


* isna( )

In [ ]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  ...   False  False   True     False
1        False     False   False  False  ...   False  False  False     False
2        False     False   False  False  ...   False  False   True     False

[3 rows x 12 columns]

In [ ]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

* fillna( )

In [ ]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  C000         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  C000         S

[3 rows x 12 columns]

In [ ]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(titanic_df['Embarked'].fillna('S'))
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### 8.   Data processing with apply lambda

* lambda
      ex) lambda x: x**2
          x -> input parameter
          x**2 -> result value(return value)
          If use lots of parameters, use map function


In [ ]:
def get_square(a):
  return a**2
print("general function's result:", get_square(3))

lambda_square = lambda x: x**2
print("lambda function's result:", lambda_square(3))

general function's result: 9
lambda function's result: 9


In [ ]:
a = [1,2,3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [ ]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [ ]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(5)

Age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult
3  35.0       Adult
4  35.0       Adult

In [ ]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [ ]:
def get_category(age):
  cat = ''
  if age<=15: cat = 'Baby'
  elif age<=12: cat = 'Child'
  elif age<=18: cat = 'Teenager'
  elif age<=25: cat = 'Student'
  elif age<=35: cat = 'Young Adult'
  elif age<=60: cat = 'Adult'
  else: cat = 'Elderly'
  return cat

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age','Age_cat']].head(5)

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult